package com.hindbiswas.jhp.engine;

public enum IssueType {
    INCLUDE_CYCLE,
    MISSING_VARIABLE,
    FUNCTION_ERROR,
    EXPRESSION_ERROR,
    MISSING_INCLUDE,
    INCLUDE_NOT_IN_BASE_DIR,
    INCLUDE_MAX_DEPTH,
    INCLUDE_ERROR,
    UNKNOWN_ELEMENT,
    FUNCTION_CALL_ERROR
}